---
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - github:
      owner: mhutter
      name: homebrew-tap
    folder: Formula
    homepage: 'https://github.com/mhutter/keygen'
    description: CLI tool to genereate base64-encoded AES keys
    test: |
      system "#{bin}/keygen 1 | grep -q '..=='"
